In [119]:
import pandas as pd
import numpy as np

In [120]:
df = pd.read_csv('train-3.csv')
data = df.copy()
df

C:\Users\ppmel\AppData\Local\Temp\ipykernel_30776\4257513045.py:1: DtypeWarning: Columns (26) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('train-3.csv')

,ID,Customer_ID,Month,Name,Age,SSN,Occupation,Annual_Income,Monthly_Inhand_Salary,Num_Bank_Accounts,...,Credit_Mix,Outstanding_Debt,Credit_Utilization_Ratio,Credit_History_Age,Payment_of_Min_Amount,Total_EMI_per_month,Amount_invested_monthly,Payment_Behaviour,Monthly_Balance,Credit_Score
0,0x1602,CUS_0xd40,January,Aaron Maashoh,23,821-00-0265,Scientist,19114.12,1824.843333,3,...,_,809.98,26.822620,22 Years and 1 Months,No,49.574949,80.41529543900253,High_spent_Small_value_payments,312.49408867943663,Good
1,0x1603,CUS_0xd40,February,Aaron Maashoh,23,821-00-0265,Scientist,19114.12,NaN,3,...,Good,809.98,31.944960,NaN,No,49.574949,118.28022162236736,Low_spent_Large_value_payments,284.62916249607184,Good
2,0x1604,CUS_0xd40,March,Aaron Maashoh,-500,821-00-0265,Scientist,19114.12,NaN,3,...,Good,809.98,28.609352,22 Years and 3 Months,No,49.574949,81.699521264648,Low_spent_Medium_value_payments,331.2098628537912,Good
3,0x1605,CUS_0xd40,April,Aaron Maashoh,23,821-00-0265,Scientist,19114.12,NaN,3,...,Good,809.98,31.377862,22 Years and 4 Months,No,49.574949,199.4580743910713,Low_spent_Small_value_payments,223.45130972736786,Good
4,0x1606,CUS_0xd40,May,Aaron Maashoh,23,821-00-0265,Scientist,19114.12,1824.843333,3,...,Good,809.98,24.797347,22 Years and 5 Months,No,49.574949,41.420153086217326,High_spent_Medium_value_payments,341.48923103222177,Good
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,0x25fe9,CUS_0x942c,April,Nicks,25,078-73-5990,Mechanic,39628.99,3359.415833,4,...,_,502.38,34.663572,31 Years and 6 Months,No,35.104023,60.97133255718485,High_spent_Large_value_payments,479.866228,Poor
99996,0x25fea,CUS_0x942c,May,Nicks,25,078-73-5990,Mechanic,39628.99,3359.415833,4,...,_,502.38,40.565631,31 Years and 7 Months,No,35.104023,54.18595028760385,High_spent_Medium_value_payments,496.65161,Poor
99997,0x25feb,CUS_0x942c,June,Nicks,25,078-73-5990,Mechanic,39628.99,3359.415833,4,...,Good,502.38,41.255522,31 Years and 8 Months,No,35.104023,24.02847744864441,High_spent_Large_value_payments,516.809083,Poor
99998,0x25fec,CUS_0x942c,July,Nicks,25,078-73-5990,Mechanic,39628.99,3359.415833,4,...,Good,502.38,33.638208,31 Years and 9 Months,No,35.104023,251.67258219721603,Low_spent_Large_value_payments,319.164979,Standard
99999,0x25fed,CUS_0x942c,August,Nicks,25,078-73-5990,Mechanic,39628.99_,3359.415833,4,...,Good,502.38,34.192463,31 Years and 10 Months,No,35.104023,167.1638651610451,!@9#%8,393.673696,Poor

In [121]:

pd.DataFrame(data.isnull().sum()).T

,ID,Customer_ID,Month,Name,Age,SSN,Occupation,Annual_Income,Monthly_Inhand_Salary,Num_Bank_Accounts,...,Credit_Mix,Outstanding_Debt,Credit_Utilization_Ratio,Credit_History_Age,Payment_of_Min_Amount,Total_EMI_per_month,Amount_invested_monthly,Payment_Behaviour,Monthly_Balance,Credit_Score
0,0,0,0,9985,0,0,0,0,15002,0,...,0,0,0,9030,0,0,4479,0,1200,0

In [122]:
pd.DataFrame(data.isna().mean() * 100).T

,ID,Customer_ID,Month,Name,Age,SSN,Occupation,Annual_Income,Monthly_Inhand_Salary,Num_Bank_Accounts,...,Credit_Mix,Outstanding_Debt,Credit_Utilization_Ratio,Credit_History_Age,Payment_of_Min_Amount,Total_EMI_per_month,Amount_invested_monthly,Payment_Behaviour,Monthly_Balance,Credit_Score
0,0.0,0.0,0.0,9.985,0.0,0.0,0.0,0.0,15.002,0.0,...,0.0,0.0,0.0,9.03,0.0,0.0,4.479,0.0,1.2,0.0

In [123]:
# Eliminar columnas basura

data.drop(columns=["ID" , "Customer_ID" , "Month" , "Name" , "SSN"], inplace=True)

In [124]:
data

,Age,Occupation,Annual_Income,Monthly_Inhand_Salary,Num_Bank_Accounts,Num_Credit_Card,Interest_Rate,Num_of_Loan,Type_of_Loan,Delay_from_due_date,...,Credit_Mix,Outstanding_Debt,Credit_Utilization_Ratio,Credit_History_Age,Payment_of_Min_Amount,Total_EMI_per_month,Amount_invested_monthly,Payment_Behaviour,Monthly_Balance,Credit_Score
0,23,Scientist,19114.12,1824.843333,3,4,3,4,"Auto Loan, Credit-Builder Loan, Personal Loan,...",3,...,_,809.98,26.822620,22 Years and 1 Months,No,49.574949,80.41529543900253,High_spent_Small_value_payments,312.49408867943663,Good
1,23,Scientist,19114.12,NaN,3,4,3,4,"Auto Loan, Credit-Builder Loan, Personal Loan,...",-1,...,Good,809.98,31.944960,NaN,No,49.574949,118.28022162236736,Low_spent_Large_value_payments,284.62916249607184,Good
2,-500,Scientist,19114.12,NaN,3,4,3,4,"Auto Loan, Credit-Builder Loan, Personal Loan,...",3,...,Good,809.98,28.609352,22 Years and 3 Months,No,49.574949,81.699521264648,Low_spent_Medium_value_payments,331.2098628537912,Good
3,23,Scientist,19114.12,NaN,3,4,3,4,"Auto Loan, Credit-Builder Loan, Personal Loan,...",5,...,Good,809.98,31.377862,22 Years and 4 Months,No,49.574949,199.4580743910713,Low_spent_Small_value_payments,223.45130972736786,Good
4,23,Scientist,19114.12,1824.843333,3,4,3,4,"Auto Loan, Credit-Builder Loan, Personal Loan,...",6,...,Good,809.98,24.797347,22 Years and 5 Months,No,49.574949,41.420153086217326,High_spent_Medium_value_payments,341.48923103222177,Good
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,25,Mechanic,39628.99,3359.415833,4,6,7,2,"Auto Loan, and Student Loan",23,...,_,502.38,34.663572,31 Years and 6 Months,No,35.104023,60.97133255718485,High_spent_Large_value_payments,479.866228,Poor
99996,25,Mechanic,39628.99,3359.415833,4,6,7,2,"Auto Loan, and Student Loan",18,...,_,502.38,40.565631,31 Years and 7 Months,No,35.104023,54.18595028760385,High_spent_Medium_value_payments,496.65161,Poor
99997,25,Mechanic,39628.99,3359.415833,4,6,5729,2,"Auto Loan, and Student Loan",27,...,Good,502.38,41.255522,31 Years and 8 Months,No,35.104023,24.02847744864441,High_spent_Large_value_payments,516.809083,Poor
99998,25,Mechanic,39628.99,3359.415833,4,6,7,2,"Auto Loan, and Student Loan",20,...,Good,502.38,33.638208,31 Years and 9 Months,No,35.104023,251.67258219721603,Low_spent_Large_value_payments,319.164979,Standard
99999,25,Mechanic,39628.99_,3359.415833,4,6,7,2,"Auto Loan, and Student Loan",18,...,Good,502.38,34.192463,31 Years and 10 Months,No,35.104023,167.1638651610451,!@9#%8,393.673696,Poor

In [125]:
pd.DataFrame(data.isnull().sum()).T

,Age,Occupation,Annual_Income,Monthly_Inhand_Salary,Num_Bank_Accounts,Num_Credit_Card,Interest_Rate,Num_of_Loan,Type_of_Loan,Delay_from_due_date,...,Credit_Mix,Outstanding_Debt,Credit_Utilization_Ratio,Credit_History_Age,Payment_of_Min_Amount,Total_EMI_per_month,Amount_invested_monthly,Payment_Behaviour,Monthly_Balance,Credit_Score
0,0,0,0,15002,0,0,0,0,11408,0,...,0,0,0,9030,0,0,4479,0,1200,0

In [126]:
pd.DataFrame(data.isna().mean() * 100).T

,Age,Occupation,Annual_Income,Monthly_Inhand_Salary,Num_Bank_Accounts,Num_Credit_Card,Interest_Rate,Num_of_Loan,Type_of_Loan,Delay_from_due_date,...,Credit_Mix,Outstanding_Debt,Credit_Utilization_Ratio,Credit_History_Age,Payment_of_Min_Amount,Total_EMI_per_month,Amount_invested_monthly,Payment_Behaviour,Monthly_Balance,Credit_Score
0,0.0,0.0,0.0,15.002,0.0,0.0,0.0,0.0,11.408,0.0,...,0.0,0.0,0.0,9.03,0.0,0.0,4.479,0.0,1.2,0.0

In [127]:
data = data.replace([r"_+", r"!@9#%8"], "", regex=True)
data

,Age,Occupation,Annual_Income,Monthly_Inhand_Salary,Num_Bank_Accounts,Num_Credit_Card,Interest_Rate,Num_of_Loan,Type_of_Loan,Delay_from_due_date,...,Credit_Mix,Outstanding_Debt,Credit_Utilization_Ratio,Credit_History_Age,Payment_of_Min_Amount,Total_EMI_per_month,Amount_invested_monthly,Payment_Behaviour,Monthly_Balance,Credit_Score
0,23,Scientist,19114.12,1824.843333,3,4,3,4,"Auto Loan, Credit-Builder Loan, Personal Loan,...",3,...,,809.98,26.822620,22 Years and 1 Months,No,49.574949,80.41529543900253,HighspentSmallvaluepayments,312.49408867943663,Good
1,23,Scientist,19114.12,NaN,3,4,3,4,"Auto Loan, Credit-Builder Loan, Personal Loan,...",-1,...,Good,809.98,31.944960,NaN,No,49.574949,118.28022162236736,LowspentLargevaluepayments,284.62916249607184,Good
2,-500,Scientist,19114.12,NaN,3,4,3,4,"Auto Loan, Credit-Builder Loan, Personal Loan,...",3,...,Good,809.98,28.609352,22 Years and 3 Months,No,49.574949,81.699521264648,LowspentMediumvaluepayments,331.2098628537912,Good
3,23,Scientist,19114.12,NaN,3,4,3,4,"Auto Loan, Credit-Builder Loan, Personal Loan,...",5,...,Good,809.98,31.377862,22 Years and 4 Months,No,49.574949,199.4580743910713,LowspentSmallvaluepayments,223.45130972736786,Good
4,23,Scientist,19114.12,1824.843333,3,4,3,4,"Auto Loan, Credit-Builder Loan, Personal Loan,...",6,...,Good,809.98,24.797347,22 Years and 5 Months,No,49.574949,41.420153086217326,HighspentMediumvaluepayments,341.48923103222177,Good
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,25,Mechanic,39628.99,3359.415833,4,6,7,2,"Auto Loan, and Student Loan",23,...,,502.38,34.663572,31 Years and 6 Months,No,35.104023,60.97133255718485,HighspentLargevaluepayments,479.866228,Poor
99996,25,Mechanic,39628.99,3359.415833,4,6,7,2,"Auto Loan, and Student Loan",18,...,,502.38,40.565631,31 Years and 7 Months,No,35.104023,54.18595028760385,HighspentMediumvaluepayments,496.65161,Poor
99997,25,Mechanic,39628.99,3359.415833,4,6,5729,2,"Auto Loan, and Student Loan",27,...,Good,502.38,41.255522,31 Years and 8 Months,No,35.104023,24.02847744864441,HighspentLargevaluepayments,516.809083,Poor
99998,25,Mechanic,39628.99,3359.415833,4,6,7,2,"Auto Loan, and Student Loan",20,...,Good,502.38,33.638208,31 Years and 9 Months,No,35.104023,251.67258219721603,LowspentLargevaluepayments,319.164979,Standard
99999,25,Mechanic,39628.99,3359.415833,4,6,7,2,"Auto Loan, and Student Loan",18,...,Good,502.38,34.192463,31 Years and 10 Months,No,35.104023,167.1638651610451,,393.673696,Poor

In [128]:
data = data.replace("", np.nan)

In [129]:
data

,Age,Occupation,Annual_Income,Monthly_Inhand_Salary,Num_Bank_Accounts,Num_Credit_Card,Interest_Rate,Num_of_Loan,Type_of_Loan,Delay_from_due_date,...,Credit_Mix,Outstanding_Debt,Credit_Utilization_Ratio,Credit_History_Age,Payment_of_Min_Amount,Total_EMI_per_month,Amount_invested_monthly,Payment_Behaviour,Monthly_Balance,Credit_Score
0,23,Scientist,19114.12,1824.843333,3,4,3,4,"Auto Loan, Credit-Builder Loan, Personal Loan,...",3,...,NaN,809.98,26.822620,22 Years and 1 Months,No,49.574949,80.41529543900253,HighspentSmallvaluepayments,312.49408867943663,Good
1,23,Scientist,19114.12,NaN,3,4,3,4,"Auto Loan, Credit-Builder Loan, Personal Loan,...",-1,...,Good,809.98,31.944960,NaN,No,49.574949,118.28022162236736,LowspentLargevaluepayments,284.62916249607184,Good
2,-500,Scientist,19114.12,NaN,3,4,3,4,"Auto Loan, Credit-Builder Loan, Personal Loan,...",3,...,Good,809.98,28.609352,22 Years and 3 Months,No,49.574949,81.699521264648,LowspentMediumvaluepayments,331.2098628537912,Good
3,23,Scientist,19114.12,NaN,3,4,3,4,"Auto Loan, Credit-Builder Loan, Personal Loan,...",5,...,Good,809.98,31.377862,22 Years and 4 Months,No,49.574949,199.4580743910713,LowspentSmallvaluepayments,223.45130972736786,Good
4,23,Scientist,19114.12,1824.843333,3,4,3,4,"Auto Loan, Credit-Builder Loan, Personal Loan,...",6,...,Good,809.98,24.797347,22 Years and 5 Months,No,49.574949,41.420153086217326,HighspentMediumvaluepayments,341.48923103222177,Good
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,25,Mechanic,39628.99,3359.415833,4,6,7,2,"Auto Loan, and Student Loan",23,...,NaN,502.38,34.663572,31 Years and 6 Months,No,35.104023,60.97133255718485,HighspentLargevaluepayments,479.866228,Poor
99996,25,Mechanic,39628.99,3359.415833,4,6,7,2,"Auto Loan, and Student Loan",18,...,NaN,502.38,40.565631,31 Years and 7 Months,No,35.104023,54.18595028760385,HighspentMediumvaluepayments,496.65161,Poor
99997,25,Mechanic,39628.99,3359.415833,4,6,5729,2,"Auto Loan, and Student Loan",27,...,Good,502.38,41.255522,31 Years and 8 Months,No,35.104023,24.02847744864441,HighspentLargevaluepayments,516.809083,Poor
99998,25,Mechanic,39628.99,3359.415833,4,6,7,2,"Auto Loan, and Student Loan",20,...,Good,502.38,33.638208,31 Years and 9 Months,No,35.104023,251.67258219721603,LowspentLargevaluepayments,319.164979,Standard
99999,25,Mechanic,39628.99,3359.415833,4,6,7,2,"Auto Loan, and Student Loan",18,...,Good,502.38,34.192463,31 Years and 10 Months,No,35.104023,167.1638651610451,NaN,393.673696,Poor

In [130]:
cols = [
    "Credit_Mix",
    "Occupation",
    "Type_of_Loan",
    "Credit_History_Age",
    "Payment_Behaviour"    
]
for col in cols:
    data[col] = data[col].fillna("Missing")

data

,Age,Occupation,Annual_Income,Monthly_Inhand_Salary,Num_Bank_Accounts,Num_Credit_Card,Interest_Rate,Num_of_Loan,Type_of_Loan,Delay_from_due_date,...,Credit_Mix,Outstanding_Debt,Credit_Utilization_Ratio,Credit_History_Age,Payment_of_Min_Amount,Total_EMI_per_month,Amount_invested_monthly,Payment_Behaviour,Monthly_Balance,Credit_Score
0,23,Scientist,19114.12,1824.843333,3,4,3,4,"Auto Loan, Credit-Builder Loan, Personal Loan,...",3,...,Missing,809.98,26.822620,22 Years and 1 Months,No,49.574949,80.41529543900253,HighspentSmallvaluepayments,312.49408867943663,Good
1,23,Scientist,19114.12,NaN,3,4,3,4,"Auto Loan, Credit-Builder Loan, Personal Loan,...",-1,...,Good,809.98,31.944960,Missing,No,49.574949,118.28022162236736,LowspentLargevaluepayments,284.62916249607184,Good
2,-500,Scientist,19114.12,NaN,3,4,3,4,"Auto Loan, Credit-Builder Loan, Personal Loan,...",3,...,Good,809.98,28.609352,22 Years and 3 Months,No,49.574949,81.699521264648,LowspentMediumvaluepayments,331.2098628537912,Good
3,23,Scientist,19114.12,NaN,3,4,3,4,"Auto Loan, Credit-Builder Loan, Personal Loan,...",5,...,Good,809.98,31.377862,22 Years and 4 Months,No,49.574949,199.4580743910713,LowspentSmallvaluepayments,223.45130972736786,Good
4,23,Scientist,19114.12,1824.843333,3,4,3,4,"Auto Loan, Credit-Builder Loan, Personal Loan,...",6,...,Good,809.98,24.797347,22 Years and 5 Months,No,49.574949,41.420153086217326,HighspentMediumvaluepayments,341.48923103222177,Good
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,25,Mechanic,39628.99,3359.415833,4,6,7,2,"Auto Loan, and Student Loan",23,...,Missing,502.38,34.663572,31 Years and 6 Months,No,35.104023,60.97133255718485,HighspentLargevaluepayments,479.866228,Poor
99996,25,Mechanic,39628.99,3359.415833,4,6,7,2,"Auto Loan, and Student Loan",18,...,Missing,502.38,40.565631,31 Years and 7 Months,No,35.104023,54.18595028760385,HighspentMediumvaluepayments,496.65161,Poor
99997,25,Mechanic,39628.99,3359.415833,4,6,5729,2,"Auto Loan, and Student Loan",27,...,Good,502.38,41.255522,31 Years and 8 Months,No,35.104023,24.02847744864441,HighspentLargevaluepayments,516.809083,Poor
99998,25,Mechanic,39628.99,3359.415833,4,6,7,2,"Auto Loan, and Student Loan",20,...,Good,502.38,33.638208,31 Years and 9 Months,No,35.104023,251.67258219721603,LowspentLargevaluepayments,319.164979,Standard
99999,25,Mechanic,39628.99,3359.415833,4,6,7,2,"Auto Loan, and Student Loan",18,...,Good,502.38,34.192463,31 Years and 10 Months,No,35.104023,167.1638651610451,Missing,393.673696,Poor

In [131]:
cols = [
    "Age",
    "Annual_Income",
    "Num_of_Loan",
    "Num_of_Delayed_Payment",
    "Changed_Credit_Limit",
    "Outstanding_Debt",
    "Amount_invested_monthly",
    "Monthly_Balance"
]

for col in cols:
    data[col] = data[col].astype(str).str.replace(r"[^\d.]", "", regex=True)
    data[col] = pd.to_numeric(data[col], errors="coerce")
    
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 23 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   Age                       100000 non-null  int64
 1   Occupation                100000 non-null  object
 2   Annual_Income             100000 non-null  float64
 3   Monthly_Inhand_Salary     84998 non-null   float64
 4   Num_Bank_Accounts         100000 non-null  int64
 5   Num_Credit_Card           100000 non-null  int64
 6   Interest_Rate             100000 non-null  int64
 7   Num_of_Loan               100000 non-null  int64
 8   Type_of_Loan              100000 non-null  object
 9   Delay_from_due_date       100000 non-null  int64
 10  Num_of_Delayed_Payment    92998 non-null   float64
 11  Changed_Credit_Limit      97909 non-null   float64
 12  Num_Credit_Inquiries      98035 non-null   float64
 13  Credit_Mix                100000 non-null  object
 14  Outstanding_Debt          100000 non-null  float64
 15  Credit_Utilization_Ratio  100000 non-null  float64
 16  Credit_History_Age        100000 non-null  object
 17  Payment_of_Min_Amount     100000 non-null  object
 18  Total_EMI_per_month       100000 non-null  float64
 19  Amount_invested_monthly   95521 non-null   float64
 20  Payment_Behaviour         100000 non-null  object
 21  Monthly_Balance           98800 non-null   float64
 22  Credit_Score              100000 non-null  object
dtypes: float64(10), int64(6), object(7)
memory usage: 17.5+ MB

In [132]:
import re

def convert_to_months(x):
    if pd.isna(x):
        return np.nan
    years = re.search(r'(\d+)\s+Years', x)
    months = re.search(r'(\d+)\s+Months', x)
    
    years = int(years.group(1)) if years else 0
    months = int(months.group(1)) if months else 0
    
    return years * 12 + months

data["Credit_History_Age"] = data["Credit_History_Age"].apply(convert_to_months)
data["Credit_History_Age"] = data["Credit_History_Age"] / 12

In [133]:
data

,Age,Occupation,Annual_Income,Monthly_Inhand_Salary,Num_Bank_Accounts,Num_Credit_Card,Interest_Rate,Num_of_Loan,Type_of_Loan,Delay_from_due_date,...,Credit_Mix,Outstanding_Debt,Credit_Utilization_Ratio,Credit_History_Age,Payment_of_Min_Amount,Total_EMI_per_month,Amount_invested_monthly,Payment_Behaviour,Monthly_Balance,Credit_Score
0,23,Scientist,19114.12,1824.843333,3,4,3,4,"Auto Loan, Credit-Builder Loan, Personal Loan,...",3,...,Missing,809.98,26.822620,22.083333,No,49.574949,80.415295,HighspentSmallvaluepayments,312.494089,Good
1,23,Scientist,19114.12,NaN,3,4,3,4,"Auto Loan, Credit-Builder Loan, Personal Loan,...",-1,...,Good,809.98,31.944960,0.000000,No,49.574949,118.280222,LowspentLargevaluepayments,284.629162,Good
2,500,Scientist,19114.12,NaN,3,4,3,4,"Auto Loan, Credit-Builder Loan, Personal Loan,...",3,...,Good,809.98,28.609352,22.250000,No,49.574949,81.699521,LowspentMediumvaluepayments,331.209863,Good
3,23,Scientist,19114.12,NaN,3,4,3,4,"Auto Loan, Credit-Builder Loan, Personal Loan,...",5,...,Good,809.98,31.377862,22.333333,No,49.574949,199.458074,LowspentSmallvaluepayments,223.451310,Good
4,23,Scientist,19114.12,1824.843333,3,4,3,4,"Auto Loan, Credit-Builder Loan, Personal Loan,...",6,...,Good,809.98,24.797347,22.416667,No,49.574949,41.420153,HighspentMediumvaluepayments,341.489231,Good
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,25,Mechanic,39628.99,3359.415833,4,6,7,2,"Auto Loan, and Student Loan",23,...,Missing,502.38,34.663572,31.500000,No,35.104023,60.971333,HighspentLargevaluepayments,479.866228,Poor
99996,25,Mechanic,39628.99,3359.415833,4,6,7,2,"Auto Loan, and Student Loan",18,...,Missing,502.38,40.565631,31.583333,No,35.104023,54.185950,HighspentMediumvaluepayments,496.651610,Poor
99997,25,Mechanic,39628.99,3359.415833,4,6,5729,2,"Auto Loan, and Student Loan",27,...,Good,502.38,41.255522,31.666667,No,35.104023,24.028477,HighspentLargevaluepayments,516.809083,Poor
99998,25,Mechanic,39628.99,3359.415833,4,6,7,2,"Auto Loan, and Student Loan",20,...,Good,502.38,33.638208,31.750000,No,35.104023,251.672582,LowspentLargevaluepayments,319.164979,Standard
99999,25,Mechanic,39628.99,3359.415833,4,6,7,2,"Auto Loan, and Student Loan",18,...,Good,502.38,34.192463,31.833333,No,35.104023,167.163865,Missing,393.673696,Poor

In [134]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 23 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   Age                       100000 non-null  int64
 1   Occupation                100000 non-null  object
 2   Annual_Income             100000 non-null  float64
 3   Monthly_Inhand_Salary     84998 non-null   float64
 4   Num_Bank_Accounts         100000 non-null  int64
 5   Num_Credit_Card           100000 non-null  int64
 6   Interest_Rate             100000 non-null  int64
 7   Num_of_Loan               100000 non-null  int64
 8   Type_of_Loan              100000 non-null  object
 9   Delay_from_due_date       100000 non-null  int64
 10  Num_of_Delayed_Payment    92998 non-null   float64
 11  Changed_Credit_Limit      97909 non-null   float64
 12  Num_Credit_Inquiries      98035 non-null   float64
 13  Credit_Mix                100000 non-null  object
 14  Outstanding_Debt          100000 non-null  float64
 15  Credit_Utilization_Ratio  100000 non-null  float64
 16  Credit_History_Age        100000 non-null  float64
 17  Payment_of_Min_Amount     100000 non-null  object
 18  Total_EMI_per_month       100000 non-null  float64
 19  Amount_invested_monthly   95521 non-null   float64
 20  Payment_Behaviour         100000 non-null  object
 21  Monthly_Balance           98800 non-null   float64
 22  Credit_Score              100000 non-null  object
dtypes: float64(11), int64(6), object(6)
memory usage: 17.5+ MB

In [135]:
data["Age_invalid"] = data["Age"].isna().astype(int)

data.loc[(data["Age"] < 18) | (data["Age"] > 100), "Age"] = np.nan

median_age = data["Age"].median()
data["Age"] = data["Age"].fillna(median_age)

In [136]:
data

,Age,Occupation,Annual_Income,Monthly_Inhand_Salary,Num_Bank_Accounts,Num_Credit_Card,Interest_Rate,Num_of_Loan,Type_of_Loan,Delay_from_due_date,...,Outstanding_Debt,Credit_Utilization_Ratio,Credit_History_Age,Payment_of_Min_Amount,Total_EMI_per_month,Amount_invested_monthly,Payment_Behaviour,Monthly_Balance,Credit_Score,Age_invalid
0,23.0,Scientist,19114.12,1824.843333,3,4,3,4,"Auto Loan, Credit-Builder Loan, Personal Loan,...",3,...,809.98,26.822620,22.083333,No,49.574949,80.415295,HighspentSmallvaluepayments,312.494089,Good,0
1,23.0,Scientist,19114.12,NaN,3,4,3,4,"Auto Loan, Credit-Builder Loan, Personal Loan,...",-1,...,809.98,31.944960,0.000000,No,49.574949,118.280222,LowspentLargevaluepayments,284.629162,Good,0
2,34.0,Scientist,19114.12,NaN,3,4,3,4,"Auto Loan, Credit-Builder Loan, Personal Loan,...",3,...,809.98,28.609352,22.250000,No,49.574949,81.699521,LowspentMediumvaluepayments,331.209863,Good,0
3,23.0,Scientist,19114.12,NaN,3,4,3,4,"Auto Loan, Credit-Builder Loan, Personal Loan,...",5,...,809.98,31.377862,22.333333,No,49.574949,199.458074,LowspentSmallvaluepayments,223.451310,Good,0
4,23.0,Scientist,19114.12,1824.843333,3,4,3,4,"Auto Loan, Credit-Builder Loan, Personal Loan,...",6,...,809.98,24.797347,22.416667,No,49.574949,41.420153,HighspentMediumvaluepayments,341.489231,Good,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,25.0,Mechanic,39628.99,3359.415833,4,6,7,2,"Auto Loan, and Student Loan",23,...,502.38,34.663572,31.500000,No,35.104023,60.971333,HighspentLargevaluepayments,479.866228,Poor,0
99996,25.0,Mechanic,39628.99,3359.415833,4,6,7,2,"Auto Loan, and Student Loan",18,...,502.38,40.565631,31.583333,No,35.104023,54.185950,HighspentMediumvaluepayments,496.651610,Poor,0
99997,25.0,Mechanic,39628.99,3359.415833,4,6,5729,2,"Auto Loan, and Student Loan",27,...,502.38,41.255522,31.666667,No,35.104023,24.028477,HighspentLargevaluepayments,516.809083,Poor,0
99998,25.0,Mechanic,39628.99,3359.415833,4,6,7,2,"Auto Loan, and Student Loan",20,...,502.38,33.638208,31.750000,No,35.104023,251.672582,LowspentLargevaluepayments,319.164979,Standard,0
99999,25.0,Mechanic,39628.99,3359.415833,4,6,7,2,"Auto Loan, and Student Loan",18,...,502.38,34.192463,31.833333,No,35.104023,167.163865,Missing,393.673696,Poor,0

In [137]:

invalid_mask = data["Num_of_Loan"] > 50

# Crear indicador correctamente
data["Num_of_Loan_invalid"] = invalid_mask.astype(int)

# Convertir inválidos en NaN
data.loc[invalid_mask, "Num_of_Loan"] = np.nan

# Imputar
median_val = data["Num_of_Loan"].median()
data["Num_of_Loan"] = data["Num_of_Loan"].fillna(median_val)

In [138]:
data["Num_Bank_Accounts_invalid"] = data["Num_Bank_Accounts"].isna().astype(int)

data.loc[(data["Num_Bank_Accounts"] < 0) | (data["Num_Bank_Accounts"] > 20), "Num_Bank_Accounts"] = np.nan

median_BA = data["Num_Bank_Accounts"].median()
data["Num_Bank_Accounts"] = data["Num_Bank_Accounts"].fillna(median_BA)

In [139]:

invalid_mask = data["Num_Credit_Card"] > 50

# Crear indicador correctamente
data["Num_Credit_Card_invalid"] = invalid_mask.astype(int)

# Convertir inválidos en NaN
data.loc[invalid_mask, "Num_Credit_Card"] = np.nan

# Imputar
median_cc = data["Num_Credit_Card"].median()
data["Num_Credit_Card"] = data["Num_Credit_Card"].fillna(median_cc)

In [140]:
data["Interest_Rate_invalid"] = data["Interest_Rate"].isna().astype(int)

data.loc[(data["Interest_Rate"] > 100), "Interest_Rate"] = np.nan

median_ir = data["Interest_Rate"].median()
data["Interest_Rate"] = data["Interest_Rate"].fillna(median_ir)

In [141]:
data[["Num_of_Loan","Num_Bank_Accounts","Interest_Rate" , "Num_Credit_Card"]].describe()

         Num_of_Loan  Num_Bank_Accounts  Interest_Rate  Num_Credit_Card
count  100000.000000      100000.000000  100000.000000    100000.000000
mean        3.515950           5.364180      14.515560         5.536430
std         2.432794           2.575733       8.712266         2.151232
min         0.000000           0.000000       1.000000         0.000000
25%         2.000000           3.000000       8.000000         4.000000
50%         3.000000           5.000000      13.000000         5.000000
75%         5.000000           7.000000      20.000000         7.000000
max        50.000000          18.000000     100.000000        50.000000

In [142]:
data[[
    "Annual_Income",
    "Outstanding_Debt",
    "Total_EMI_per_month",
    "Credit_Utilization_Ratio"
]].describe()

,Annual_Income,Outstanding_Debt,Total_EMI_per_month,Credit_Utilization_Ratio
count,1.000000e+05,100000.000000,100000.000000,100000.000000
mean,1.764157e+05,1426.220376,1403.118217,32.285173
std,1.429618e+06,1155.129026,8306.041270,5.116875
min,7.005930e+03,0.230000,0.000000,20.000000
25%,1.945750e+04,566.072500,30.306660,28.052567
50%,3.757861e+04,1166.155000,69.249473,32.305784
75%,7.279092e+04,1945.962500,161.224249,36.496663
max,2.419806e+07,4998.070000,82331.000000,50.000000

In [143]:
data

,Age,Occupation,Annual_Income,Monthly_Inhand_Salary,Num_Bank_Accounts,Num_Credit_Card,Interest_Rate,Num_of_Loan,Type_of_Loan,Delay_from_due_date,...,Total_EMI_per_month,Amount_invested_monthly,Payment_Behaviour,Monthly_Balance,Credit_Score,Age_invalid,Num_of_Loan_invalid,Num_Bank_Accounts_invalid,Num_Credit_Card_invalid,Interest_Rate_invalid
0,23.0,Scientist,19114.12,1824.843333,3.0,4.0,3.0,4.0,"Auto Loan, Credit-Builder Loan, Personal Loan,...",3,...,49.574949,80.415295,HighspentSmallvaluepayments,312.494089,Good,0,0,0,0,0
1,23.0,Scientist,19114.12,NaN,3.0,4.0,3.0,4.0,"Auto Loan, Credit-Builder Loan, Personal Loan,...",-1,...,49.574949,118.280222,LowspentLargevaluepayments,284.629162,Good,0,0,0,0,0
2,34.0,Scientist,19114.12,NaN,3.0,4.0,3.0,4.0,"Auto Loan, Credit-Builder Loan, Personal Loan,...",3,...,49.574949,81.699521,LowspentMediumvaluepayments,331.209863,Good,0,0,0,0,0
3,23.0,Scientist,19114.12,NaN,3.0,4.0,3.0,4.0,"Auto Loan, Credit-Builder Loan, Personal Loan,...",5,...,49.574949,199.458074,LowspentSmallvaluepayments,223.451310,Good,0,0,0,0,0
4,23.0,Scientist,19114.12,1824.843333,3.0,4.0,3.0,4.0,"Auto Loan, Credit-Builder Loan, Personal Loan,...",6,...,49.574949,41.420153,HighspentMediumvaluepayments,341.489231,Good,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,25.0,Mechanic,39628.99,3359.415833,4.0,6.0,7.0,2.0,"Auto Loan, and Student Loan",23,...,35.104023,60.971333,HighspentLargevaluepayments,479.866228,Poor,0,0,0,0,0
99996,25.0,Mechanic,39628.99,3359.415833,4.0,6.0,7.0,2.0,"Auto Loan, and Student Loan",18,...,35.104023,54.185950,HighspentMediumvaluepayments,496.651610,Poor,0,0,0,0,0
99997,25.0,Mechanic,39628.99,3359.415833,4.0,6.0,13.0,2.0,"Auto Loan, and Student Loan",27,...,35.104023,24.028477,HighspentLargevaluepayments,516.809083,Poor,0,0,0,0,0
99998,25.0,Mechanic,39628.99,3359.415833,4.0,6.0,7.0,2.0,"Auto Loan, and Student Loan",20,...,35.104023,251.672582,LowspentLargevaluepayments,319.164979,Standard,0,0,0,0,0
99999,25.0,Mechanic,39628.99,3359.415833,4.0,6.0,7.0,2.0,"Auto Loan, and Student Loan",18,...,35.104023,167.163865,Missing,393.673696,Poor,0,0,0,0,0

In [144]:
data["Payment_of_Min_Amount"] = data["Payment_of_Min_Amount"].astype(str).str.replace("NM", "No", regex=True)
data

,Age,Occupation,Annual_Income,Monthly_Inhand_Salary,Num_Bank_Accounts,Num_Credit_Card,Interest_Rate,Num_of_Loan,Type_of_Loan,Delay_from_due_date,...,Total_EMI_per_month,Amount_invested_monthly,Payment_Behaviour,Monthly_Balance,Credit_Score,Age_invalid,Num_of_Loan_invalid,Num_Bank_Accounts_invalid,Num_Credit_Card_invalid,Interest_Rate_invalid
0,23.0,Scientist,19114.12,1824.843333,3.0,4.0,3.0,4.0,"Auto Loan, Credit-Builder Loan, Personal Loan,...",3,...,49.574949,80.415295,HighspentSmallvaluepayments,312.494089,Good,0,0,0,0,0
1,23.0,Scientist,19114.12,NaN,3.0,4.0,3.0,4.0,"Auto Loan, Credit-Builder Loan, Personal Loan,...",-1,...,49.574949,118.280222,LowspentLargevaluepayments,284.629162,Good,0,0,0,0,0
2,34.0,Scientist,19114.12,NaN,3.0,4.0,3.0,4.0,"Auto Loan, Credit-Builder Loan, Personal Loan,...",3,...,49.574949,81.699521,LowspentMediumvaluepayments,331.209863,Good,0,0,0,0,0
3,23.0,Scientist,19114.12,NaN,3.0,4.0,3.0,4.0,"Auto Loan, Credit-Builder Loan, Personal Loan,...",5,...,49.574949,199.458074,LowspentSmallvaluepayments,223.451310,Good,0,0,0,0,0
4,23.0,Scientist,19114.12,1824.843333,3.0,4.0,3.0,4.0,"Auto Loan, Credit-Builder Loan, Personal Loan,...",6,...,49.574949,41.420153,HighspentMediumvaluepayments,341.489231,Good,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,25.0,Mechanic,39628.99,3359.415833,4.0,6.0,7.0,2.0,"Auto Loan, and Student Loan",23,...,35.104023,60.971333,HighspentLargevaluepayments,479.866228,Poor,0,0,0,0,0
99996,25.0,Mechanic,39628.99,3359.415833,4.0,6.0,7.0,2.0,"Auto Loan, and Student Loan",18,...,35.104023,54.185950,HighspentMediumvaluepayments,496.651610,Poor,0,0,0,0,0
99997,25.0,Mechanic,39628.99,3359.415833,4.0,6.0,13.0,2.0,"Auto Loan, and Student Loan",27,...,35.104023,24.028477,HighspentLargevaluepayments,516.809083,Poor,0,0,0,0,0
99998,25.0,Mechanic,39628.99,3359.415833,4.0,6.0,7.0,2.0,"Auto Loan, and Student Loan",20,...,35.104023,251.672582,LowspentLargevaluepayments,319.164979,Standard,0,0,0,0,0
99999,25.0,Mechanic,39628.99,3359.415833,4.0,6.0,7.0,2.0,"Auto Loan, and Student Loan",18,...,35.104023,167.163865,Missing,393.673696,Poor,0,0,0,0,0

In [145]:
data["Credit_Score"].value_counts()
data["Credit_Score"].value_counts(normalize=True)

Credit_Score
Standard    0.53174
Poor        0.28998
Good        0.17828
Name: proportion, dtype: float64

In [146]:
data["Payment_of_Min_Amount"].unique()

array(['No', 'Yes'], dtype=object)

In [147]:
data.to_csv("clean_data.csv")

In [148]:
num_cols = data.select_dtypes(include=["int64", "float64"]).columns

data[num_cols].isna().sum().sort_values(ascending=False)

Monthly_Inhand_Salary        15002
Num_of_Delayed_Payment        7002
Amount_invested_monthly       4479
Changed_Credit_Limit          2091
Num_Credit_Inquiries          1965
Monthly_Balance               1200
Interest_Rate                    0
Num_Credit_Card                  0
Num_Bank_Accounts                0
Annual_Income                    0
Age                              0
Outstanding_Debt                 0
Num_of_Loan                      0
Delay_from_due_date              0
Credit_History_Age               0
Credit_Utilization_Ratio         0
Total_EMI_per_month              0
Age_invalid                      0
Num_of_Loan_invalid              0
Num_Bank_Accounts_invalid        0
Num_Credit_Card_invalid          0
Interest_Rate_invalid            0
dtype: int64

In [149]:
for col in num_cols:
    if data[col].isna().sum() > 0:
        data[col + "_missing"] = data[col].isna().astype(int)
        data[col] = data[col].fillna(data[col].median())

In [150]:
num_cols = data.select_dtypes(include=["int64", "float64"]).columns

data[num_cols].isna().sum().sort_values(ascending=False)

Age                                0
Annual_Income                      0
Monthly_Inhand_Salary              0
Num_Bank_Accounts                  0
Num_Credit_Card                    0
Interest_Rate                      0
Num_of_Loan                        0
Delay_from_due_date                0
Num_of_Delayed_Payment             0
Changed_Credit_Limit               0
Num_Credit_Inquiries               0
Outstanding_Debt                   0
Credit_Utilization_Ratio           0
Credit_History_Age                 0
Total_EMI_per_month                0
Amount_invested_monthly            0
Monthly_Balance                    0
Age_invalid                        0
Num_of_Loan_invalid                0
Num_Bank_Accounts_invalid          0
Num_Credit_Card_invalid            0
Interest_Rate_invalid              0
Monthly_Inhand_Salary_missing      0
Num_of_Delayed_Payment_missing     0
Changed_Credit_Limit_missing       0
Num_Credit_Inquiries_missing       0
Amount_invested_monthly_missing    0
Monthly_Balance_missing            0
dtype: int64

In [151]:
data

,Age,Occupation,Annual_Income,Monthly_Inhand_Salary,Num_Bank_Accounts,Num_Credit_Card,Interest_Rate,Num_of_Loan,Type_of_Loan,Delay_from_due_date,...,Num_of_Loan_invalid,Num_Bank_Accounts_invalid,Num_Credit_Card_invalid,Interest_Rate_invalid,Monthly_Inhand_Salary_missing,Num_of_Delayed_Payment_missing,Changed_Credit_Limit_missing,Num_Credit_Inquiries_missing,Amount_invested_monthly_missing,Monthly_Balance_missing
0,23.0,Scientist,19114.12,1824.843333,3.0,4.0,3.0,4.0,"Auto Loan, Credit-Builder Loan, Personal Loan,...",3,...,0,0,0,0,0,0,0,0,0,0
1,23.0,Scientist,19114.12,3093.745000,3.0,4.0,3.0,4.0,"Auto Loan, Credit-Builder Loan, Personal Loan,...",-1,...,0,0,0,0,1,1,0,0,0,0
2,34.0,Scientist,19114.12,3093.745000,3.0,4.0,3.0,4.0,"Auto Loan, Credit-Builder Loan, Personal Loan,...",3,...,0,0,0,0,1,0,1,0,0,0
3,23.0,Scientist,19114.12,3093.745000,3.0,4.0,3.0,4.0,"Auto Loan, Credit-Builder Loan, Personal Loan,...",5,...,0,0,0,0,1,0,0,0,0,0
4,23.0,Scientist,19114.12,1824.843333,3.0,4.0,3.0,4.0,"Auto Loan, Credit-Builder Loan, Personal Loan,...",6,...,0,0,0,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,25.0,Mechanic,39628.99,3359.415833,4.0,6.0,7.0,2.0,"Auto Loan, and Student Loan",23,...,0,0,0,0,0,0,0,0,0,0
99996,25.0,Mechanic,39628.99,3359.415833,4.0,6.0,7.0,2.0,"Auto Loan, and Student Loan",18,...,0,0,0,0,0,0,0,0,0,0
99997,25.0,Mechanic,39628.99,3359.415833,4.0,6.0,13.0,2.0,"Auto Loan, and Student Loan",27,...,0,0,0,0,0,0,0,0,0,0
99998,25.0,Mechanic,39628.99,3359.415833,4.0,6.0,7.0,2.0,"Auto Loan, and Student Loan",20,...,0,0,0,0,0,1,0,0,0,0
99999,25.0,Mechanic,39628.99,3359.415833,4.0,6.0,7.0,2.0,"Auto Loan, and Student Loan",18,...,0,0,0,0,0,0,0,0,0,0

In [152]:
data["Delay_from_due_date"].describe()

count    100000.000000
mean         21.068780
std          14.860104
min          -5.000000
25%          10.000000
50%          18.000000
75%          28.000000
max          67.000000
Name: Delay_from_due_date, dtype: float64

In [153]:
data.to_csv("clean_data2.csv")

In [154]:
data["Credit_Score"].value_counts()
data["Credit_Score"].value_counts(normalize=True)

Credit_Score
Standard    0.53174
Poor        0.28998
Good        0.17828
Name: proportion, dtype: float64

In [155]:
data

,Age,Occupation,Annual_Income,Monthly_Inhand_Salary,Num_Bank_Accounts,Num_Credit_Card,Interest_Rate,Num_of_Loan,Type_of_Loan,Delay_from_due_date,...,Num_of_Loan_invalid,Num_Bank_Accounts_invalid,Num_Credit_Card_invalid,Interest_Rate_invalid,Monthly_Inhand_Salary_missing,Num_of_Delayed_Payment_missing,Changed_Credit_Limit_missing,Num_Credit_Inquiries_missing,Amount_invested_monthly_missing,Monthly_Balance_missing
0,23.0,Scientist,19114.12,1824.843333,3.0,4.0,3.0,4.0,"Auto Loan, Credit-Builder Loan, Personal Loan,...",3,...,0,0,0,0,0,0,0,0,0,0
1,23.0,Scientist,19114.12,3093.745000,3.0,4.0,3.0,4.0,"Auto Loan, Credit-Builder Loan, Personal Loan,...",-1,...,0,0,0,0,1,1,0,0,0,0
2,34.0,Scientist,19114.12,3093.745000,3.0,4.0,3.0,4.0,"Auto Loan, Credit-Builder Loan, Personal Loan,...",3,...,0,0,0,0,1,0,1,0,0,0
3,23.0,Scientist,19114.12,3093.745000,3.0,4.0,3.0,4.0,"Auto Loan, Credit-Builder Loan, Personal Loan,...",5,...,0,0,0,0,1,0,0,0,0,0
4,23.0,Scientist,19114.12,1824.843333,3.0,4.0,3.0,4.0,"Auto Loan, Credit-Builder Loan, Personal Loan,...",6,...,0,0,0,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,25.0,Mechanic,39628.99,3359.415833,4.0,6.0,7.0,2.0,"Auto Loan, and Student Loan",23,...,0,0,0,0,0,0,0,0,0,0
99996,25.0,Mechanic,39628.99,3359.415833,4.0,6.0,7.0,2.0,"Auto Loan, and Student Loan",18,...,0,0,0,0,0,0,0,0,0,0
99997,25.0,Mechanic,39628.99,3359.415833,4.0,6.0,13.0,2.0,"Auto Loan, and Student Loan",27,...,0,0,0,0,0,0,0,0,0,0
99998,25.0,Mechanic,39628.99,3359.415833,4.0,6.0,7.0,2.0,"Auto Loan, and Student Loan",20,...,0,0,0,0,0,1,0,0,0,0
99999,25.0,Mechanic,39628.99,3359.415833,4.0,6.0,7.0,2.0,"Auto Loan, and Student Loan",18,...,0,0,0,0,0,0,0,0,0,0

In [159]:
df = pd.read_csv("train.csv")
df

,Age,Occupation,Annual_Income,Monthly_Inhand_Salary,Num_Bank_Accounts,Num_Credit_Card,Interest_Rate,Num_of_Loan,Type_of_Loan,Delay_from_due_date,...,Num_Bank_Accounts_missing,Num_Credit_Card_missing,Interest_Rate_missing,Num_of_Loan_missing,Num_of_Delayed_Payment_missing,Changed_Credit_Limit_missing,Num_Credit_Inquiries_missing,Credit_History_Age_missing,Amount_invested_monthly_missing,Monthly_Balance_missing
0,23.0,Scientist,19114.12,1824.843333,3.0,4.0,3.0,4.0,"Auto Loan, Credit-Builder Loan, Personal Loan,...",3,...,0,0,0,0,0,0,0,0,0,0
1,23.0,Scientist,19114.12,3093.745000,3.0,4.0,3.0,4.0,"Auto Loan, Credit-Builder Loan, Personal Loan,...",-1,...,0,0,0,0,1,0,0,1,0,0
2,34.0,Scientist,19114.12,3093.745000,3.0,4.0,3.0,4.0,"Auto Loan, Credit-Builder Loan, Personal Loan,...",3,...,0,0,0,0,0,1,0,0,0,0
3,23.0,Scientist,19114.12,3093.745000,3.0,4.0,3.0,4.0,"Auto Loan, Credit-Builder Loan, Personal Loan,...",5,...,0,0,0,0,0,0,0,0,0,0
4,23.0,Scientist,19114.12,1824.843333,3.0,4.0,3.0,4.0,"Auto Loan, Credit-Builder Loan, Personal Loan,...",6,...,0,0,0,0,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,25.0,Mechanic,39628.99,3359.415833,4.0,6.0,7.0,2.0,"Auto Loan, and Student Loan",23,...,0,0,0,0,0,0,0,0,0,0
99996,25.0,Mechanic,39628.99,3359.415833,4.0,6.0,7.0,2.0,"Auto Loan, and Student Loan",18,...,0,0,0,0,0,0,0,0,0,0
99997,25.0,Mechanic,39628.99,3359.415833,4.0,6.0,13.0,2.0,"Auto Loan, and Student Loan",27,...,0,0,1,0,0,0,0,0,0,0
99998,25.0,Mechanic,39628.99,3359.415833,4.0,6.0,7.0,2.0,"Auto Loan, and Student Loan",20,...,0,0,0,0,1,0,0,0,0,0
99999,25.0,Mechanic,39628.99,3359.415833,4.0,6.0,7.0,2.0,"Auto Loan, and Student Loan",18,...,0,0,0,0,0,0,0,0,0,0

In [160]:
df = pd.read_csv("clean_train.csv")
df

,ID,Customer_ID,Month,Name,Age,SSN,Annual_Income,Monthly_Inhand_Salary,Num_Bank_Accounts,Num_Credit_Card,...,Occupation_Scientist,Occupation_Teacher,Occupation_Writer,Credit_Mix_Bad,Credit_Mix_Good,Credit_Mix_Missing,Credit_Mix_Standard,Payment_of_Min_Amount_Missing,Payment_of_Min_Amount_No,Payment_of_Min_Amount_Yes
0,0x1602,CUS_0xd40,January,Aaron Maashoh,23.0,821-00-0265,19114.12,1824.843333,3.0,4.0,...,True,False,False,False,False,True,False,False,True,False
1,0x1603,CUS_0xd40,February,Aaron Maashoh,23.0,821-00-0265,19114.12,1824.843333,3.0,4.0,...,True,False,False,False,True,False,False,False,True,False
2,0x1604,CUS_0xd40,March,Aaron Maashoh,23.0,821-00-0265,19114.12,1824.843333,3.0,4.0,...,True,False,False,False,True,False,False,False,True,False
3,0x1605,CUS_0xd40,April,Aaron Maashoh,23.0,821-00-0265,19114.12,1824.843333,3.0,4.0,...,True,False,False,False,True,False,False,False,True,False
4,0x1606,CUS_0xd40,May,Aaron Maashoh,23.0,821-00-0265,19114.12,1824.843333,3.0,4.0,...,True,False,False,False,True,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,0x25fe9,CUS_0x942c,April,Nicks,25.0,078-73-5990,39628.99,3359.415833,4.0,6.0,...,False,False,False,False,False,True,False,False,True,False
99996,0x25fea,CUS_0x942c,May,Nicks,25.0,078-73-5990,39628.99,3359.415833,4.0,6.0,...,False,False,False,False,False,True,False,False,True,False
99997,0x25feb,CUS_0x942c,June,Nicks,25.0,078-73-5990,39628.99,3359.415833,4.0,6.0,...,False,False,False,False,True,False,False,False,True,False
99998,0x25fec,CUS_0x942c,July,Nicks,25.0,078-73-5990,39628.99,3359.415833,4.0,6.0,...,False,False,False,False,True,False,False,False,True,False
99999,0x25fed,CUS_0x942c,August,Nicks,25.0,078-73-5990,39628.99,3359.415833,4.0,6.0,...,False,False,False,False,True,False,False,False,True,False